create table candidato (
	ID BIGINT AUTO_INCREMENT UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    SEXO CHAR(1) NOT NULL DEFAULT 'M',
    NOTA INTEGER NOT NULL,
    LOGRADOURO VARCHAR(200),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    UF CHAR(2),
    PRIMARY KEY(ID)
);

CREATE INDEX CANDIDATO_API_CANDIDATO_ID ON candidato(ID);
CREATE INDEX CANDIDATO_API_CANDIDATO_NOME ON candidato(NOME);
CREATE INDEX CANDIDATO_API_CANDIDATO_NASCIMENTO ON candidato(NASCIMENTO);
CREATE INDEX CANDIDATO_API_CANDIDATO_SEXO ON candidato(SEXO);
CREATE INDEX CANDIDATO_API_CANDIDATO_NOTA ON candidato(NOTA);